on: [push, pull_request]
name: CI
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go vet
      continue-on-error: false
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: vet
    - name: staticcheck
      continue-on-error: false
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: staticcheck
    - name: gosec
      # Gives too many false positives.
      continue-on-error: true
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: sec
        flags: "-exclude=G104"
    - name: misspell
      continue-on-error: false
      run: |
        go get -u github.com/client9/misspell/cmd/misspell
        $(go env GOPATH)/bin/misspell -locale US *.md $(find . -name '*.go')
  build:
    name: Build the executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
    - name: Build
      run: |
        set -ex

        GOARCH=amd64
        build () {
          GOOS=$1 make eth2-monitor && install -v bin/eth2-monitor build/eth2-monitor-$1
        }

        mkdir -p build
        build linux
        build darwin
        build freebsd
        build windows

        ( cd build
          sha256sum * > sha256sums.txt
        )

    - name: Upload binaries
      uses: actions/upload-artifact@master
      with:
        name: Executables
        path: "build"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          build/*
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
